### ISSUE TITLE
Roadmap to first revision

### ISSUE THREAD

**Issue by croth1** [soedinglab/BaMM_webserver#69]
# Roadmap

- [x] update to new version of BaMM & AURRC scripts (#56)
- [x] implement and validate initalizing q from the data (#65)
- [x] decide on number of cores per job & check parallelization 
- [x] add motif occurrences plot for unequal sequence lengths & test for correctness
- [x] redesign motif search output page (#68)
- [x] making the webserver public (#61)
- [x] create new databases and upload to our gwdg server
- [x] update the documentation to the latest server version, include important details on (How to read our higher-order logos, performance plots, ...)
- [x] flip the logo plots on the result page
- [x] check impressum
- [x] change motif scanning e-value to p-value
- [x] update motif refinement UI page.

**Comment by croth1** [comment]
:tada:
